"""v0.38.4 — the native glass (macOS shell) + a real dock icon.

The darwin window stops being an opaque box: pywebview goes transparent,
an AppKit material view (NSGlassEffectView — Apple's Liquid Glass — on
macOS 26+, NSVisualEffectView vibrancy behind-window on every older
release) is inserted behind the WKWebView, the page body steps aside, and
the dock icon becomes a brand-kit artifact (assets/icon.icns, generated by
scripts/build_brand.py) instead of a CI-only file.
"""

import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAIN = (ROOT / "src" / "suravidl_engine" / "__main__.py").read_text()
CSS = (ROOT / "src" / "suravidl_engine" / "web" / "style.css").read_text()
BUILDER = (ROOT / "scripts" / "build_brand.py").read_text()

from suravidl_engine import __main__ as engine_main


# ---------- the shell ----------
def test_the_darwin_window_is_created_transparent():
    assert 'transparent=sys.platform == "darwin"' in MAIN


def test_the_window_falls_back_when_transparent_is_unsupported():
    assert "except TypeError" in MAIN  # older pywebview without the kwarg


def test_material_is_darwin_only():
    # real behaviour on this Linux box: nothing to do
    assert engine_main._apply_native_material(object()) is False


# ---------- the material layer (fake AppKit, real logic) ----------
class _FakeView:
    def __init__(self, name="NSView"):
        self.name = name
        self._subviews = []
        self.frame = None
        self.added = []
        self.kv = {}

    def subviews(self):
        return list(self._subviews)

    @classmethod
    def alloc(cls):
        # +alloc in AppKit: a class method returning a fresh instance
        return cls()

    def init(self):
        return self

    def setFrame_(self, frame):
        self.frame = frame

    def bounds(self):
        return (0, 0, 100, 100)

    def setMaterial_(self, m):
        self.material = m

    def setBlendingMode_(self, b):
        self.blending = b

    def setState_(self, s):
        self.state = s

    def setAppearance_(self, a):
        self.appearance = a

    def addSubview_positioned_relativeTo_(self, sub, pos, rel):
        self.added.append((sub, pos, rel))

    def setValue_forKey_(self, v, k):
        self.kv[k] = v


class _FakeNative:
    def __init__(self, content):
        self._content = content

    def contentView(self):
        return self._content


class _FakeWindow:
    def __init__(self, native):
        self.native = native
        self.js = []

    def evaluate_js(self, code):
        self.js.append(code)
        return "dark"


def _fake_appkit(with_glass=True):
    class AppKit:
        NSWindowBelow = -1
        NSVisualEffectMaterialUnderWindowBackground = 6
        NSVisualEffectBlendingModeBehindWindow = 2
        NSVisualEffectStateActive = 1

    # real AppKit always carries NSVisualEffectView; the glass class is
    # macOS 26+
    AppKit.NSVisualEffectView = type("NSVisualEffectView", (_FakeView,), {})
    AppKit.NSGlassEffectView = (
        type("NSGlassEffectView", (_FakeView,), {}) if with_glass else None)
    return AppKit


def _fake_window_with_webview():
    content = _FakeView("NSContentView")
    inner = type("WKWebView", (_FakeView,), {})()   # the class name is what's matched
    content._subviews = [inner]
    return _FakeWindow(_FakeNative(content)), content, inner


def test_a_glass_layer_goes_behind_the_webview():
    window, content, inner = _fake_window_with_webview()
    assert engine_main._install_material(window, _fake_appkit(True), None) is True
    sub, pos, rel = content.added[0]
    assert sub.__class__.__name__ == "NSGlassEffectView"
    assert pos == -1 and rel is inner              # behind the web content
    assert inner.kv.get("drawsBackground") is False  # the page shows it


def test_older_macos_falls_back_to_vibrancy():
    window, content, _ = _fake_window_with_webview()
    assert engine_main._install_material(window, _fake_appkit(False), None) is True
    sub = content.added[0][0]
    assert sub.__class__.__name__ == "NSVisualEffectView"
    assert sub.blending == 2                       # .behindWindow


def test_no_pyobjc_or_no_native_means_no_material():
    window, _, _ = _fake_window_with_webview()
    assert engine_main._install_material(window, None, None) is False
    assert engine_main._install_material(_FakeWindow(None),
                                         _fake_appkit(True), None) is False


def test_the_page_steps_aside_only_when_glass_is_real(monkeypatch):
    window, _, _ = _fake_window_with_webview()
    monkeypatch.setattr(engine_main, "_apply_native_material", lambda w: False)
    engine_main._native_glass_ready(window)
    assert not any("darwin-glass" in c for c in window.js)
    monkeypatch.setattr(engine_main, "_apply_native_material", lambda w: True)
    engine_main._native_glass_ready(window)
    assert any("darwin-glass" in c for c in window.js)


# ---------- the page side ----------
def test_the_page_yields_to_the_native_material():
    assert 'html[data-host="darwin-glass"] body { background: transparent; }' in CSS


# ---------- the dock icon ----------
def _chunks(data):
    out = []
    offset = 8
    while offset < len(data):
        kind = data[offset:offset + 4]
        (length,) = struct.unpack(">I", data[offset + 4:offset + 8])
        assert length >= 8
        out.append(kind)
        offset += length
    return out


def test_the_dock_icon_is_a_brand_artifact():
    icns = ROOT / "assets" / "icon.icns"
    assert icns.exists()
    data = icns.read_bytes()
    magic, total = struct.unpack(">4sI", data[:8])
    assert magic == b"icns" and total == len(data)
    kinds = _chunks(data)
    assert b"ic10" in kinds   # the 1024 master ships in the container


def test_the_builder_generates_the_icns():
    assert "def build_icns" in BUILDER
    assert '"ic10"' in BUILDER


def test_the_bundle_uses_it_and_carries_the_version():
    spec = (ROOT / "suravidl.spec").read_text()
    assert 'assets/icon.icns' in spec
    from suravidl_engine import __version__
    assert f'"CFBundleShortVersionString": "{__version__}"' in spec