plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.chaquo.python'
}

android {
    namespace 'com.vidl.app'
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }

    defaultConfig {
        applicationId "com.vidl.app"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "0.0.1"
        ndk { abiFilters "arm64-v8a", "x86_64" }
    }
}

chaquopy {
    defaultConfig {
        buildPython "python3"
        pip {
            install "yt-dlp"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
